apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-storageclass
  # annotations:
  #   storageclass.kubernetes.io/is-default-class: "false"
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain # default value is Delete
allowVolumeExpansion: true